apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
spec:
  type: bindings.twitter
  metadata:
  - name: consumerKey
    value: "" # twitter api consumer key, required
  - name: consumerSecret
    value: "" # twitter api consumer secret, required
  - name: accessToken
    value: "" # twitter api access token, required
  - name: accessSecret
    value: "" # twitter api access secret, required
  - name: query
    value: "serverless" # use common term for demo