apiVersion: v1
kind: Namespace
metadata:
  name: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: pipeline
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
  namespace: pipeline
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
  namespace: pipeline
spec:
  type: exporters.zipkin
  metadata:
  - name: enabled
    value: "true"
  - name: exporterAddress
    value: "http://zipkin.dapr-monitoring.svc.cluster.local:9411/api/v2/spans"
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: space-config
  namespace: pipeline
spec:
  tracing:
    samplingRate: "1"