apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: note-store
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master.data.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
scopes:
- nginx-ingress