apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo-service
  labels:
    app: grpc-echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-echo-service
  template:
    metadata:
      labels:
        app: grpc-echo-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "grpc-echo-service"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "60002"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: service
        image: mchmarny/grpc-echo-service:v0.10.0
        imagePullPolicy: Always
        ports:
        - containerPort: 60002
        env:
        - name: ADDRESS
          value: ":60002"