apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweet-store
spec:
  type: state.mongodb
  metadata:
  - name: host
    value: mongo-mongodb-headless.mongo.svc.cluster.local:27017
  - name: username
    value: dapr
  - name: password
    secretKeyRef:
      name: mongo-secret
      key: password
  - name: databaseName
    value: dapr
  - name: collectionName
    value: audit
scopes:
- tweet-provider