name: git-ops release on tag

on:
  push:
    tags:
      - 'gitops-v*' # gitops-v0.1.1

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.pkg.github.com
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - name: Tidy
      run: |
        cd git-ops/app
        go mod tidy 
        go mod vendor

    - name: Test
      run: |
        cd git-ops/app
        go test -v -count=1 -race ./...

    - name: Variables
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        BUILD_TIME=$(echo $(date +"%Y-%m-%dT%T"))
        echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV

    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: ./git-ops/app
        file: ./git-ops/app/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.DEVOPS_TOKEN }}
        registry: ${{ env.REGISTRY }}
        repository: ${{ github.actor }}/dapr-demos/git-ops-app
        push: true
        tags: ${{ env.RELEASE_VERSION }}
        build-args: |
            APP_VERSION=${{ env.RELEASE_VERSION }}
            BUILD_TIME=${{ env.BUILD_TIME }}




          
  
